---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

  vars:
    backend_image: "dulanjah/devops_engineering:backend"
    frontend_image: "dulanjah/devops_engineering:frontend"
    backend_port: 3000
    frontend_port: 80
