---
###############################
# 1️⃣ GET EC2 PUBLIC IPS
###############################
- name: Get EC2 public IPs
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Gather EC2 info
      amazon.aws.ec2_instance_info:
        region: ap-south-1
        filters:
          instance-state-name: running
      register: ec2_instances

    - name: Add EC2 to dynamic inventory
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: ec2_servers
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /var/lib/jenkins/Jenkins-new-key.pem
      loop: "{{ ec2_instances.instances }}"
      when: item.public_ip_address is defined


###############################
# 2️⃣ INSTALL DOCKER + RUN CONTAINERS
###############################
- name: Deploy Docker Containers
  hosts: ec2_servers
  become: yes
  gather_facts: no

  vars:
    backend_image: "dulanjah/devops_engineering:backend"
    frontend_image: "dulanjah/devops_engineering:frontend"

  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      command: usermod -aG docker ec2-user
      ignore_errors: yes

    - name: Pull backend image
      community.docker.docker_container:
        name: backend
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"

    - name: Pull frontend image
      community.docker.docker_container:
        name: frontend
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
