---
###############################
# DEPLOY DOCKER CONTAINERS TO LOCALHOST
###############################
- name: Deploy Docker Containers on Localhost
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    backend_image: "dulanjah/devops_engineering:backend"
    frontend_image: "dulanjah/devops_engineering:frontend"
    backend_port: 3000
    frontend_port: 80

  tasks:

    - name: Pull backend image
      community.docker.docker_container:
        name: backend
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ backend_port }}:3000"

    - name: Pull frontend image
      community.docker.docker_container:
        name: frontend
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ frontend_port }}:80"

    - name: Display deployment status
      debug:
        msg:
          - "✅ Backend deployed on http://localhost:{{ backend_port }}"
          - "✅ Frontend deployed on http://localhost:{{ frontend_port }}"
